// Generated by NailHammer. DO NOT EDIT.
//
// Edit the .nh grammar and re-run `nh build --rust`. Anything changed here is
// lost on the next build.

// One module per labelled alternative. Each is a small file you own;
// this list is regenerated so a new alternative wires itself up.

pub mod block;
pub mod more_elem;
pub mod primary_elem;
pub mod primary_list;
pub mod primary_num;
pub mod primary_str;
pub mod primary_var;
pub mod program;
pub mod stmt_eval;
pub mod stmt_iff;
pub mod stmt_print;
pub mod stmt_whilst;
