# A sample configuration.

name    = "nailhammer";
version = 0.2;
stable  = false;
notes   = null;

tags = [ "parser" "codegen" "rust" ];

limits = {
  depth = 32;
  retry = 3;
  nested = { enabled = true; };
};
