//! Generates the Rust side of a NailHammer grammar (DESIGN.md milestone M2).
//!
//! Three things come out of here, and the split between them is the whole
//! answer to CLAUDE.md's complaint about unmaintainable files:
//!
//! * **Views** ([`views`]) — one struct per labelled alternative, with
//!   accessors named from the grammar's bindings. Handler code never calls
//!   `into_inner()` and never indexes children by position, so reordering a
//!   rule is a compile error rather than a silent misparse.
//! * **The trait stack and dispatch** ([`dispatch`]) — `Handlers` has one
//!   required method per labelled alternative, and a generated macro writes an
//!   impl whose bodies do nothing but delegate to a per-alternative module.
//!   Adding an alternative to the `.nh` breaks the build until a handler
//!   exists; Rust's own exhaustiveness does the checking.
//! * **Stubs** ([`stubs`]) — one small file per alternative, written once and
//!   never overwritten.

pub mod ast;
pub mod diagnostics;
pub mod drift;
pub mod dispatch;
pub mod operators;
pub mod params;
pub mod place;
mod run;
pub mod stubs;
pub mod views;

use nh_lower::Lowered;
use nh_operators::OperatorTable;
use nh_syntax::Ast;

/// A file the generator produced, and how it may be written.
pub struct GeneratedFile {
    /// Path relative to the output root.
    pub path: String,
    pub contents: String,
    pub policy: Policy,
}

/// DESIGN.md §5.4's regeneration policy, made explicit so it cannot be got
/// wrong by accident. Getting it wrong destroys user work.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Policy {
    /// Always overwritten. Carries a DO-NOT-EDIT header.
    Generated,
    /// Written once if absent. Never overwritten, never deleted.
    OnceOnly,
}

pub struct Generated {
    pub files: Vec<GeneratedFile>,
    /// Handler module names, so the caller can report orphaned stubs.
    pub handler_modules: Vec<String>,
}

/// Options that cannot be inferred from the grammar.
#[derive(Clone)]
pub struct Options {
    /// Rust path to the pest parser type produced by `#[derive(Parser)]`.
    ///
    /// Overridden from the grammar's own name by [`generate`] — `grammar Calc;`
    /// gives `crate::CalcParser` — so a caller only sets this for a project
    /// that names its parser something else.
    pub parser_type: String,
    /// Module path the generated code lives under.
    pub module_path: String,
    /// Module path the hand-written handlers live under.
    pub handlers_path: String,
}

impl Default for Options {
    fn default() -> Self {
        Options {
            parser_type: "crate::LangParser".to_string(),
            module_path: "crate::generated".to_string(),
            handlers_path: "crate::handlers".to_string(),
        }
    }
}

pub const HEADER: &str = "\
// Generated by NailHammer. DO NOT EDIT.
//
// Edit the .nh grammar and re-run `nh build --rust`. Anything changed here is
// lost on the next build.
";

pub fn generate(ast: &Ast, table: &OperatorTable, lowered: &Lowered, opts: &Options) -> Generated {
    // `grammar Calc;` means `#[derive(Parser)] pub struct CalcParser`, which is
    // what the scaffold writes and what every example uses. Deriving it here
    // rather than making both callers pass it is the same rule as everything
    // else (DESIGN §0): a value that can be worked out is not a question.
    let mut derived = opts.clone();
    if opts.parser_type == Options::default().parser_type {
        if let Some(name) = &ast.grammar_name {
            derived.parser_type = format!("crate::{}Parser", name.value);
        }
    }
    let opts = &derived;

    let mut files = Vec::new();

    files.push(GeneratedFile {
        path: "generated/ast.rs".into(),
        contents: ast::generate(lowered, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/views.rs".into(),
        contents: views::generate(lowered, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/dispatch.rs".into(),
        contents: dispatch::generate(lowered, table, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/diagnostics.rs".into(),
        contents: diagnostics::generate(lowered, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/run.rs".into(),
        contents: run::generate(lowered, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/place.rs".into(),
        contents: place::generate(lowered, opts),
        policy: Policy::Generated,
    });
    files.push(GeneratedFile {
        path: "generated/mod.rs".into(),
        contents: format!(
            "{HEADER}\n\
             pub mod ast;\npub mod diagnostics;\npub mod dispatch;\n\
             pub mod place;\npub mod run;\npub mod views;\n\n\
             pub use diagnostics::{{render_parse_error, syntax_errors}};\n\
             pub use dispatch::{{Eval, Handlers}};\n\
             pub use place::Place;\n\
             pub use run::eval_source;\n"
        ),
        policy: Policy::Generated,
    });

    let mut handler_modules = Vec::new();
    for alt in &lowered.alternatives {
        handler_modules.push(alt.pest_rule.clone());
        files.push(GeneratedFile {
            path: format!("handlers/{}.rs", alt.pest_rule),
            contents: stubs::generate(alt, opts),
            policy: Policy::OnceOnly,
        });
    }

    files.push(GeneratedFile {
        path: "handlers/mod.rs".into(),
        contents: stubs::generate_mod(lowered),
        policy: Policy::Generated,
    });

    Generated {
        files,
        handler_modules,
    }
}

/// Turns a grammar identifier into a Rust type name: `stmt_let` → `StmtLet`.
pub(crate) fn type_name(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Escapes Rust keywords so a grammar binding named `type` or `ref` can still
/// name a method.
pub fn ident(s: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
        "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
        "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
        "unsafe", "use", "where", "while", "async", "await", "box", "final", "macro", "override",
        "priv", "try", "typeof", "unsized", "virtual", "yield",
    ];
    if KEYWORDS.contains(&s) {
        format!("r#{s}")
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn type_names_are_pascal_case() {
        assert_eq!(type_name("stmt_let"), "StmtLet");
        assert_eq!(type_name("primary_num"), "PrimaryNum");
        assert_eq!(type_name("expr"), "Expr");
    }

    #[test]
    fn rust_keywords_are_escaped() {
        // A grammar may legitimately bind a field named `type` or `ref`.
        assert_eq!(ident("type"), "r#type");
        assert_eq!(ident("ref"), "r#ref");
        assert_eq!(ident("value"), "value");
    }
}
