// Generated by NailHammer. DO NOT EDIT.
//
// Edit the .nh grammar and re-run `nh build --rust`. Anything changed here is
// lost on the next build.

// One module per labelled alternative. Each is a small file you own;
// this list is regenerated so a new alternative wires itself up.

pub mod document;
pub mod entry;
pub mod value_list;
pub mod value_no;
pub mod value_null;
pub mod value_number;
pub mod value_string;
pub mod value_table;
pub mod value_yes;
