[package]
name = "nh-build"
description = "build.rs integration for NailHammer grammars"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
nh-syntax.workspace = true
nh-operators.workspace = true
nh-analysis.workspace = true
nh-lower.workspace = true
nh-codegen.workspace = true
